[package]
name = "four_bit_adder"
version = "1.0.0"
description = "A simple full-adder module"
license = "MIT"
author = "Tanishq Dubey"

[repository]
type = "git"
url = "https://github.com/narendasan/four_bit_adder"

[dependencies]
"narendasan/full_adder" = "1.0.0"